### ISSUE TITLE
Is adc available?

### ISSUE THREAD

**Issue by beckmx** [biemster/st17h66_RF#9]
Hello, I am have been following your repo from quite some time, I was wondering if you know if these chips are adc enabled? It would be nice to attach a simple sensor

**Comment by biemster** [comment]
They do have a 5-channel 12bit ADC, and an accompanying application note: https://doc.lenze.club/public/store/17H6X(Flash)/%E3%80%9006%E3%80%91%E5%BC%80%E5%8F%91%E6%96%87%E6%A1%A3/ST17H65_66_ADC_Application_Note.pdf

But I never looked into this so on the software side you are the frontrunner..
